### ISSUE TITLE
Adding an image from Galery to comment produces crash

### ISSUE THREAD

**Issue by ilyarmnzhdn** [rursache/ToDoList#1]
Xcode 11.3
Simulator iPhone 8, version 11.3

Error -> 
`*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Attempted to scroll the table view to an out-of-bounds row (2) when there are only 2 rows in section 0. Table view: <UITableView: 0x7fb000866200; frame = (0 0; 375 517); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x600003466f70>; layer = <CALayer: 0x600003bcc580>; contentOffset: {0, 0}; contentSize: {375, 404}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <ToDoList.CommentsViewController: 0x7fafff7e7510>>`

**Comment by rursache** [comment]
Fixed in https://github.com/rursache/ToDoList/commit/a996d830a24aefd5963e1874161ddd93dbfd01b5
