### ISSUE TITLE
xcode 12.0.1 build errors

### ISSUE THREAD

**Issue by andyferriby** [rursache/ToDoList#10]
Built with xcode 12.0.1
<img width="1016" alt="Screenshot 2020-10-01 at 10 51 26" src="https://user-images.githubusercontent.com/21694968/94794690-22661e80-03d4-11eb-9c1d-a25b6b43dfe2.png">

**Comment by rursache** [comment]
this is due to realm's lack of valid archs - https://github.com/realm/realm-cocoa/issues/6684

**Comment by rursache** [comment]
this got fixed in Realm v10.1.0 - https://github.com/realm/realm-cocoa/releases/tag/v10.1.0
