### ISSUE TITLE
Crash on Activate when being asked to allow notifications

### ISSUE THREAD

**Issue by TomasHubelbauer** [rursache/ToDoList#12]
Hi, I just got RSToDoList off the AppStore based on this GitHub repository. It looks great, but when I am asked to allow notifications during onboarding, when I click Activate, the app consistently crashes. But - the notifications do get enabled in the Settings it seems. I had do dismiss the prompt for notifications using the Not Now button for it to go away though, even though now in the Settings I see them enabled. The notifications work - I set a reminder and got a notification. Let me know how I can help debug the issue.

**Comment by rursache** [comment]
Thanks for your report, I'll look into it in the following days. Meantime, you can help by creating a pull request if you can fix the issue yourself.

**Comment by TomasHubelbauer** [comment]
Here is the stack trace of the issue I discovered while coming up with the fix:
<img width="920" alt="image" src="https://user-images.githubusercontent.com/6831144/148577048-c1b7d007-5f44-4461-bc4b-00ebed309b8d.png">
I am not sure how to best display the stack trace so I will just post a screenshot of the stack unwinding:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/6831144/148577166-07871e03-edfe-4f09-8443-5c6c10ea94cd.png">
Called from:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/6831144/148577230-b206ae36-2ac1-4c56-850e-c7bb28d0a52e.png">
This is the first code site in your code, in OnboardingDataSource:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/6831144/148577355-1b68d482-8b63-4701-9bc2-eb85684eb29e.png">
Called from `AppDelegate`:
<img width="918" alt="image" src="https://user-images.githubusercontent.com/6831144/148577458-772ff61f-6cf2-45d2-b709-00a21018c9bc.png">
I fixed this by just running that handler on the main thread no matter what.
