### ISSUE TITLE
Navbar acting weird

### ISSUE THREAD

**Issue by keshaaaaav** [rursache/ToDoList#15]
https://user-images.githubusercontent.com/65015627/150596620-145ae397-3f15-4e25-b991-ce98add3532a.mp4

Here's a short video, the navigation bar is transparent on app launch.
Upon scrolling, it becomes visible (in red) and goes back invisible once I stop scrolling.

**Comment by rursache** [comment]
that's the default iOS 15 behaviour, i will override it when i'll have the time to do so
pull requests are welcome

**Comment by keshaaaav** [comment]
sure, will send a pull request

**Comment by keshaaaav** [comment]
Sent! 

![Keshav's MacBook - 3TiMUIog](https://user-images.githubusercontent.com/83570000/150644824-6d55db96-0f9c-4d9a-a884-185452b2e411.png)

**Comment by rursache** [comment]
thank you
